name: Image version
description: Determines the container image version based on a git ref
inputs:
  ref:
    description: The git ref to use. Defaults to `github.ref``.
    default: ${{ github.ref }}
    required: false
outputs:
  version:
    description: The image version
    value: ${{ steps.version.outputs.version }}
runs:
  using: composite
  steps:
  - name: Determine image version
    id: version
    shell: bash
    run: printf "version=%s\n" "$("$GITHUB_ACTION_PATH/image-version.sh" "${{ github.ref }}")" >> $GITHUB_OUTPUT
