name: Image version
description: Determines the container image version based on a git ref
inputs:
  ref:
    description: The git ref to use. Defaults to `github.ref``.
    default: ${{ github.ref }}
    required: false
  prefix:
    description: Prefix to remove in tags. Defaults to `v``.
    default: v
    required: false
outputs:
  version:
    description: The image tag
    value: ${{ steps.version.outputs.version }}
runs:
  using: composite
  steps:
  - name: Determine image tag
    id: version
    shell: bash
    run: printf "version=%s\n" "$("$GITHUB_ACTION_PATH/bin/image-version" -p "${{ inputs.prefix }}" "${{ inputs.ref }}")" >> $GITHUB_OUTPUT
